apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "websocket.loadcore.keysight.com/v1alpha1",
          "kind": "Websocket",
          "metadata": {
            "name": "websocket-sample"
          },
          "spec": {
            "auth": {
              "clientId": "clt-wap",
              "enabled": true,
              "tokenEndpoint": "https://keycloak.kcos-sso.svc.cluster.local.:8443/auth/realms/keysight/protocol/openid-connect/token"
            },
            "cors": {
              "enabled": true
            },
            "database": {
              "enabled": true,
              "host": "wap-db-postgresql",
              "image": {
                "name": "bitnami/postgresql",
                "tag": "14.2.0-debian-10-r44"
              },
              "name": "wapdb",
              "port": 5432,
              "secret": {
                "key": "password",
                "name": "wap-db-postgresql-token"
              },
              "user": "user"
            },
            "fullnameOverride": "",
            "image": {
              "pullPolicy": "IfNotPresent",
              "repository": "docker-virtual-wap.artifactorylbj.it.keysight.com",
              "tagSuffix": ""
            },
            "imagePullSecrets": [],
            "ingress": {
              "annotations": {
                "nginx.ingress.kubernetes.io/proxy-body-size": "0",
                "nginx.ingress.kubernetes.io/ssl-redirect": "true"
              },
              "authAnnotations": {
                "nginx.ingress.kubernetes.io/auth-method": "POST",
                "nginx.ingress.kubernetes.io/auth-response-headers": "X-AUTH-USER",
                "nginx.ingress.kubernetes.io/auth-url": "https://127.0.0.1/token/validate",
                "nginx.ingress.kubernetes.io/configuration-snippet": "add_header Access-Control-Expose-Headers 'Content-Disposition';"
              },
              "corsAnnotations": {
                "nginx.ingress.kubernetes.io/cors-allow-credentials": "true",
                "nginx.ingress.kubernetes.io/cors-allow-headers": "authorization, x-requested-with, x-signalr-user-agent",
                "nginx.ingress.kubernetes.io/cors-allow-methods": "PUT, GET, POST, OPTIONS",
                "nginx.ingress.kubernetes.io/cors-allow-origin": "http://localhost:4200",
                "nginx.ingress.kubernetes.io/enable-cors": "true"
              },
              "enabled": true,
              "tls": [
                {
                  "hosts": [],
                  "secretName": "tls-secret"
                }
              ]
            },
            "ingressController": {
              "name": "kcos-ingress-ingress-nginx-controller",
              "namespace": "kcos-framework"
            },
            "logging": {
              "level": "info"
            },
            "nameOverride": "",
            "wap-library-chart": {
              "global": {}
            },
            "websocket": {
              "resources": {
                "limits": {
                  "cpu": "25m",
                  "memory": "100Mi"
                },
                "requests": {
                  "cpu": "25m",
                  "memory": "40Mi"
                }
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.22.2
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: websocket-service.v0.0.19
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: Websocket
        name: websockets.websocket.loadcore.keysight.com
        version: v1alpha1
  description: Keysight Websocket Operator
  displayName: Keysight Websocket Operator
  icon:
    - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+DQo8c3ZnIHhtbG5zOnN2Zz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMTQwLjY3OTYzIiBoZWlnaHQ9IjEwOS42MTAzMiIgaWQ9InN2ZzQxMjIiPg0KICA8ZGVmcyBpZD0iZGVmczQxMjQiLz4NCiAgPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTEyOS42NjAxOSwtNDc3LjU1NykiIGlkPSJsYXllcjEiPg0KICAgIDxwYXRoIGQ9Im0gMjY0LjM4ODUxLDUzNC4wNTQxNSBjIC0xLjAyNCwtMC4xNTc4MyAtMy4xODIxLC0xLjIzMzIgLTQuNzI3MjcsLTcuMTIwMjcgLTIuNDczNzQsLTkuNDIxNTEgLTMuNjQwODgsLTE3LjUwMzM4IC03LjgzMjI5LC0xNy41MDMzOCAtNC4xOTUwOSwwIC02LjA5NjI3LDguMDgxODcgLTguNTcwMDEsMTcuNTAzMzggLTEuNDY0NDMsNS41NzE0MyAtMy4wMDU5Myw3LjEyMDI3IC01LjQ3OTY4LDcuMTIwMjcgLTIuMzE5NTgsMCAtNC43MjM1OSwtMS4xMzQxIC04LjI2MTcxLC0xNS42OTc2MyBDIDIyNi40MjcyMiw1MDUuNjIwOCAyMjQuMzIwNSw0ODIuNTU3IDIxMy45NDg0LDQ4Mi41NTcgYyAtMTAuMzc5NDUsMCAtMTMuNDM2NzYsMzAuMDYyOTUgLTE0Ljc3MjcyLDM1Ljg1ODI1IC0xLjY0NDI2LDcuMTQyMjggLTUuNzI1NTgsMTUuNjQyNTcgLTEwLjg2MDI0LDE1LjY0MjU3IC01LjEzNDY3LDAgLTcuNzkxOTIsLTUuOTEyNzYgLTkuMzI5NzYsLTEyLjI1ODYxIC0yLjM1MjYzLC05LjcxNTEzIC01LjAyODIzLC0yMy43Nzk0OSAtMTEuODU0ODgsLTIzLjc3OTQ5IC02LjgzMDMxLDAgLTkuMDQ3MTMsMTEuNjQ1NjggLTEyLjA1NjczLDI0LjM2NjczIC0xLjc3MjczLDcuNDk4MzEgLTQuNjAyNDksMTEuNjcxMzcgLTkuNTc1NjcsMTEuNjcxMzcgbCAtMTAuODM4MjEsMCAwLDAuMDQ3NyBjIDEuNDE2NzEsMC40MjIwOCA0LjI0MjgsMi43NjM2OSA0Ljk3MzE4LDcuMzAwMSAxLjcxNzY3LDEwLjcwNjEgMy4wMzE2MSwxNy4zMzA4OSA2Ljc2NzkyLDE3LjMzMDg5IDMuNzM2MywwIDUuMDk0MjksLTUuNzEwOSA3LjI1OTc0LC0xNC42MTEyNCAxLjY5MTk3LC02Ljk3MzQ1IDQuMzM0NTUsLTEwLjAxNjA5IDcuNDkwOTUsLTEwLjAxNjA5IDQuNjM5MTksMCA2LjgyMjk5LDUuNjE1NDggOS4zNTkxMiwxNi4zNDcyNSA1LjA0MjksMjEuMzc5MTcgNi4xMTgyOSwzMS43MTA4OSAxNC4yNDQyLDMxLjcxMDg5IDguMDYzNTIsMCA5LjMyMjQyLC0xMC4zNTM3NSAxNC43NDMzNSwtMzEuNzEwODkgMi4zNTk5OCwtOS4yODkzNyA2Ljc2MDU5LC0xNi4zNTA5MSAxMS44OTUyNywtMTYuMzUwOTEgNS4xMzQ2NiwwIDguODAxMjIsNi44NDEzMyAxMC42NjkzOCwxMi4yOTUzIDQuMDQ0NiwxMS44MjU1MSA1LjkwOTA5LDE2LjI3NzUzIDEwLjM2NDc1LDE2LjI3NzUzIDQuNDUyMDIsMCA2Ljk2OTc5LC01LjM0Mzg4IDEwLjg5Njk1LC0xOC4yNDg0NCAyLjQ3Mzc0LC04LjEyMjI1IDIuODM3MSwtMTAuMzI0MzkgMTAuMTE1MTksLTEwLjMyNDM5IGwgMTAuOTQ4MzIsMCAwLC0wLjA1MTQgeiIgaWQ9InBhdGg0MCIgc3R5bGU9ImZpbGw6I2U5MDAyOTtmaWxsLW9wYWNpdHk6MTtmaWxsLXJ1bGU6bm9uemVybztzdHJva2U6bm9uZSIvPg0KICA8L2c+DQo8L3N2Zz4=
      mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
            - apiGroups:
                - websocket.loadcore.keysight.com
              resources:
                - websockets
                - websockets/status
                - websockets/finalizers
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - configmaps
                - services
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - '*'
            - apiGroups:
                - batch
              resources:
                - jobs
              verbs:
                - '*'
            - apiGroups:
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - '*'
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: keysight-websocket-service-controller-manager
      deployments:
        - label:
            control-plane: controller-manager
          name: keysight-websocket-service-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --secure-listen-address=0.0.0.0:8443
                      - --upstream=http://127.0.0.1:8080/
                      - --logtostderr=true
                      - --v=0
                    image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:latest
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                        protocol: TCP
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 5m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                  - args:
                      - --health-probe-bind-address=:8081
                      - --metrics-bind-address=127.0.0.1:8080
                      - --leader-elect
                      - --leader-election-id=keysight-websocket-service
                    image: prod.harbor.keysight.digital/loadcore/keysight-websocket-service:0.0.19
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 1Gi
                      requests:
                        cpu: 10m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                securityContext:
                  runAsNonRoot: true
                serviceAccountName: keysight-websocket-service-controller-manager
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: keysight-websocket-service-controller-manager
    strategy: deployment
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - loadcore
    - keysight
  links:
    - name: Keysight Websocket Service
      url: https://keysight-websocket-service.domain
  maintainers:
    - email: vlad.butusina@keysight.com
      name: Vlad Butusina
  maturity: alpha
  provider:
    name: Keysight
    url: keysight.com
  version: 0.0.19
